# Docs for the Azure Web Apps Deploy action: https://github.com/Az ure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - sssssssssssss03

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      
      - name: Run Checkstyle
        run: mvn checkstyle:check
        
      - name: Build project with Maven
        run: mvn clean install --file pom.xml
        
      - name: Dependency Test
        run: mvn dependency:analyze
        
      - name: Display target directory
        run: ls target
        
      - name: List workspace contents
        run: ls -R ${{ github.workspace }}

  dependency-check:
    runs-on: ubuntu-latest
    needs: Lint

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Dependency check
        run: mvn dependency:analyze
        

        

  unit-test:
    runs-on: ubuntu-latest
    needs: dependency-check
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          
      - name: Run unit Tests 
        run: mvn test jacoco:report
      
          

    
  package-artifact:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          
      - name: Package Artifact
        run: mvn package
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target
        
      - name: Display target directory
        run: ls target
        
      - name: List workspace contents
        run: ls -R ${{ github.workspace }}
        
        
        
      
  deploy:
    runs-on: ubuntu-latest
    needs: package-artifact

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'javacicdcase1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: '*.war'
          path: './target/*.war'
